### PR TITLE
Ocean Faucet Tweetbot

### PR DESCRIPTION
**Pull request by acolytec3**

### CODE REVIEW

**Comment by acolytec3** [comment]
Just checking in on the review of this PR.  I refactored the functions to make it more modular and added some additional tests.  Note, the Travis build fails because one of the integration tests requires a functioning faucet server to connect to.

**Comment by innoprenuer** [comment]
@acolytec3 Hey, thanks for the PR. Apparently, reviewers for this PR are quite caught up currently due to upcoming network launch. So, it might take a while before this gets reviewed. However, I will keep you upadated on this and if takes much while then we will reward you tokens. So, please give us some time. Cheers!

**Comment by acolytec3** [comment]
No problem, just wanted to make sure it hadn't gotten lost in the mix.
Thanks!

**Comment by acolytec3** [comment]
I'm assuming I should wait until it's reviewed before I submit work on
Gitcoin, right?

**Comment by innoprenuer** [comment]
@acolytec3 ideally you should submit on gitcoin first. And it taking long due to upcoming network launch. But, we will try to take it up sooner now.

**Comment by acolytec3** [comment]
Okay, I actually did that on 3/8.

**Comment by acolytec3** [comment]
What's the word on this?  I submitted this PR nearly a month ago and just want to make sure it didn't get completely lost in the mix of mainnet launch.

**Comment by jernejpregelj** [comment]
Thank you, I'll notify bounty manager to close this and give rewards.

**Comment by acolytec3** [comment]
Thanks!

**Pull request merged**
